DROP SEQUENCE BOARDNOSEQ2;
DROP SEQUENCE GROUPNOSEQ2;
DROP TABLE ANSWERBOARD2;

CREATE SEQUENCE BOARDNOSEQ2;
CREATE SEQUENCE GROUPNOSEQ2;

--글번호, 그룹번호,그룹순서,제목공백,삭제여부(Y,N)
--제목, 내용ㅇ, 작성자, 작성일
CREATE TABLE ANSWERBOARD2(
	BOARDNO NUMBER NOT NULL,
	GROUPNO NUMBER NOT NULL, 
	GROUPSEQ NUMBER NOT NULL, 
	TITLETAB NUMBER NOT NULL, 
	DELFLAG VARCHAR2(2) NOT NULL, 
	TITLE VARCHAR2(1000) NOT NULL, 
	CONTENT VARCHAR2(4000) NOT NULL, 
	WRITER VARCHAR2(500) NOT NULL, 
	REGDATE DATE NOT NULL, 
	CONSTRAINT ANSWER_BOARDNO_PK PRIMARY KEY(BOARDNO),
	CONSTRAINT ANSWER_DELFLAG_CK CHECK(DELFLAG IN('Y','N'))


);


--1 글 작성 
INSERT INTO ANSWERBOARD2
VALUES(BOARDNOSEQ2.NEXTVAL, GROUPNOSEQ2.NEXTVAL,1,0,'N','답변형 재밌다','정말 재미따?','반장',SYSDATE);

--1번글에 답글 
--UPDATE 
--INSERT


UPDATE ANSWERBOARD2 
SET GROUPSEQ = GROUPSEQ +1 
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD2 WHERE BOARDNO = 1)
AND GROUPSEQ >(SELECT GROUPSEQ FROM ANSWERBOARD2 WHERE BOARDNO = 1);


INSERT INTO ANSWERBOARD2 
VALUES( BOARDNOSEQ2.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD2 WHERE BOARDNO = 1),
		(SELECT GROUPSEQ FROM ANSWERBOARD2 WHERE BOARDNO = 1)+1,
		(SELECT TITLETAB FROM ANSWERBOARD2 WHERE BOARDNO = 1)+1,
		'N',
		'RE:답변형 재밌다.',
		'진짜 재밌는거 맞아?',
		'강사',
		SYSDATE
		
);	



SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG, TITLE, CONTENT, WRITER, REGDATE 
FROM ANSWERBOARD2 
ORDER BY GROUPNO DESC, GROUPSEQ;